#Auto-incremented version code
#Mon Aug 31 05:07:39 WAT 2026
APP_VERSION_CODE=4
APP_VERSION_NAME=1
RELEASE_KEY_ALIAS=key0
RELEASE_KEY_PASSWORD=@Opeyemi0
RELEASE_STORE_FILE=C\:/Users/USER/release.keystore
RELEASE_STORE_PASSWORD=@Opeyemi0
android.nonTransitiveRClass=true
android.useAndroidX=true
kotlin.code.style=official
kotlin.daemon.jvmargs=-Xmx3072M
kotlin.native.ignoreDisabledTargets=true
org.gradle.caching=true
org.gradle.configuration-cache=true
org.gradle.jvmargs=-Xmx4096M -Dfile.encoding\=UTF-8
