package com.timeline.util

object AppStrings {
    const val AppName = "Timeline"

    // Auth Screen
    const val AuthWelcomeTitle = "Welcome to $AppName"
    const val AuthWelcomeSubtitle = "Turn your app usage into clarity."
    const val AuthSignInGoogle = "Sign in with Google"
    const val AuthSignInApple = "Sign in with Apple"
    const val AuthOr = "or"
    const val AuthEmailPlaceholder = "Email address"
    const val AuthDontHaveAccount = "Don't have an account?"
    const val AuthSignInWithGoogleLink = "Sign in with Google"

    // Onboarding Intro
    const val OnboardingWelcomeTitle = "Welcome to $AppName"
    const val OnboardingWelcomeSubtitle = "A private timeline of your phone activity—so you can understand your time, not lose it."
    const val OnboardingValuePropTitle = "We build your activity timeline"
    const val OnboardingValuePropSubtitle = "Timeline quietly records when you use apps so we can show you a clear, honest view of your day."
    const val OnboardingOverviewTitle = "To make this work, we need 3 permissions"
    const val OnboardingOverviewSubtitle = "These let Timeline run in the background and keep your data accurate and private."

    // Onboarding Mode Selection & Value Props
    const val OnboardingModeTitle = "Choose your tracking experience"
    const val OnboardingModeSubtitle = "Select the depth of timeline clarity and background automation you want."
    const val OnboardingProModeTitle = "Timeline Pro (Full Automation)"
    const val OnboardingProModeDesc = "Automatic screen capture and text recognition for high-fidelity timeline recall."
    const val OnboardingProModeButton = "Select Pro Experience"
    const val OnboardingProModeBadge = "RECOMMENDED"
    const val OnboardingBasicModeTitle = "Basic Tracking (Usage Stats)"
    const val OnboardingBasicModeDesc = "App launch frequency and usage duration tracking without screenshot captures."
    const val OnboardingBasicModeButton = "Select Basic Experience"

    const val OnboardingValueProp1Title = "On-Device & Private"
    const val OnboardingValueProp1Desc = "Everything stays on your phone. We never sell or share your activity data."
    const val OnboardingValueProp2Title = "Smart AI Narratives"
    const val OnboardingValueProp2Desc = "Understand where your time went with concise, meaningful activity summaries."

    const val OnboardingStackTitle = "Permissions Setup"
    const val OnboardingStackSubtitle = "Enable permissions to activate your automated timeline."

    // Accessibility Flow
    const val OnboardingAccessibilityIntroTitle = "Accessibility is required to build your timeline"
    const val OnboardingAccessibilityIntro1 = "See when you open or switch apps so we can record activity accurately."
    const val OnboardingAccessibilityIntro2 = "Understand what's on your screen to group and label your activity."
    const val OnboardingAccessibilityIntro3 = "Run in the background to keep your timeline complete."
    const val OnboardingAccessibilityIntroFooter = "Your data stays on your device. We never collect, share, or sell your information."

    const val OnboardingAccessibilityGrantTitle = "Accessibility access"
    const val OnboardingAccessibilityGrantSubtitle = "Lets Timeline observe what you're doing on your device so we can build an accurate timeline."

    const val OnboardingAccessibilitySuccessTitle = "Nice! Accessibility access is enabled"
    const val OnboardingAccessibilitySuccessSubtitle = "Timeline can now build a more accurate activity timeline."

    const val OnboardingAccessibilityFailureTitle = "Accessibility access not granted yet"
    const val OnboardingAccessibilityFailureSubtitle = "You can still use Timeline, but your timeline may be incomplete or less accurate."

    // Usage Flow
    const val OnboardingUsageIntroTitle = "We need to see app usage"
    const val OnboardingUsageIntroSubtitle = "Usage access helps Timeline understand which apps you use and when."
    const val OnboardingUsageIntro1 = "See which apps you use and how long."
    const val OnboardingUsageIntro2 = "Build daily and weekly insights from your activity."
    const val OnboardingUsageIntro3 = "Everything stays private and on your device."
    const val OnboardingUsageIntro4 = "We don't access content. We only collect app names and usage time."

    const val OnboardingUsageGrantTitle = "App Usage access"
    const val OnboardingUsageGrantSubtitle = "Lets Timeline see which apps you use and for how long."

    const val OnboardingUsageSuccessTitle = "Nice! Usage access is enabled"
    const val OnboardingUsageSuccessSubtitle = "Timeline can now see which apps you use and how long."

    const val OnboardingUsageFailureTitle = "Usage access not granted yet"
    const val OnboardingUsageFailureSubtitle = "You can still continue, but Timeline won't be able to show app usage or insights."

    // Notifications Flow
    const val OnboardingNotificationsIntroTitle = "Stay informed"
    const val OnboardingNotificationsIntroSubtitle = "Notifications keep Timeline running in the background."
    const val OnboardingNotificationsIntro1 = "Reminds you about your day with smart summaries."
    const val OnboardingNotificationsIntro2 = "Keeps your timeline up to date even when the app is in the background."
    const val OnboardingNotificationsIntro3 = "You're in control. You can turn off notifications anytime."

    const val OnboardingNotificationsGrantTitle = "Notifications"
    const val OnboardingNotificationsGrantSubtitle = "Keeps Timeline running in the background and reminds you about your day."

    // Final Step
    const val OnboardingAllSetTitle = "All set! Timeline is ready"
    const val OnboardingAllSetSubtitle = "We'll start building your timeline in the background."
    const val OnboardingAllSet1 = "Private by default"
    const val OnboardingAllSet2 = "On your device"
    const val OnboardingAllSet3 = "You're in control"

    // Buttons
    const val ButtonNext = "Next"
    const val ButtonGrantAccess = "Grant Access"
    const val ButtonEnable = "Enable"
    const val ButtonContinue = "Continue"
    const val ButtonTryAgain = "Try Again"
    const val ButtonNotNow = "Not now"
    const val ButtonMaybeLater = "Maybe later"
    const val ButtonOpenTimeline = "Open Timeline"
    const val ButtonUnderstandContinue = "I Understand & Continue"
    const val ButtonOpenSettings = "Open Settings"
    const val ButtonContinueSettings = "Continue to Settings"
    const val ButtonAlreadyGranted = "Already Granted"
    const val ButtonSkipForNow = "Skip for Now"
    const val ButtonCancel = "Cancel"

    // Legacy / Other
    const val PermissionAllSetTitle = "You're all set!"
    const val PermissionAlmostThereTitle = "Almost there..."
    const val PermissionAllSetSubtitle = "Everything is ready for your timeline."
    const val PermissionAlmostThereSubtitle = "To show you real insights, we need access to how you use your apps."
    const val PermissionAllowButton = "Allow Access"
    const val PermissionNotNowButton = "Not Now"

    // Permission Details
    const val PermissionUsageTitle = "Usage access"
    const val PermissionUsageDesc = "Analyze how you spend time."
    const val PermissionUsageIllustration = "illustrations/usage_access.png"
    const val PermissionOverlayTitle = "Display over other apps"
    const val PermissionOverlayDesc = "Enable background screen capture support."
    const val PermissionOverlayIllustration = "illustrations/overlay.png"
    const val PermissionNotificationsTitle = "Notifications"
    const val PermissionNotificationsDesc = "Deliver important alerts and reminders."
    const val PermissionNotificationsIllustration = "illustrations/notifications.png"
    const val PermissionAccessibilityTitle = "Accessibility Service"
    const val PermissionAccessibilityDesc = "Powers advanced automated activity tracking."
    const val PermissionAccessibilityIllustration = "illustrations/accessibility.png"
    const val PermissionBatteryTitle = "Battery Optimization"
    const val PermissionBatteryDesc = "Prevents background service interruptions."
    const val PermissionBatteryIllustration = "illustrations/battery.png"

    // Timeline Screen
    const val TimelineTitle = "Timeline"
    const val TimelineToday = "Today"
    const val TimelineTimeOfDay = "Time of Day"
    const val TimelineSettings = "Settings"
    const val TimelineNoActivity = "No activity recorded"
    const val TimelineTotalUsage = "Total usage"
    const val TimelineSessionsCount = "Sessions"
    const val TimelineMostUsed = "Most used"
    const val TimelineOk = "OK"
    const val TimelineCancel = "Cancel"
    const val CommonVersion = "Version %s"
    const val CommonInsight = "Insight"
    const val CommonCollapse = "Collapse"
    const val CommonH = "h"
    const val CommonM = "m"

    // Highlight Screen
    const val HighlightTitle = "Highlight"
    const val HighlightSample = "Sample"
    const val HighlightPickDate = "Pick Date"
    const val HighlightAnalyzing = "Analyzing..."
    const val HighlightTags = "Tags"
    const val HighlightContentStarts = "Content Starts"
    const val HighlightSessionEnds = "Session Ends"
    const val HighlightNoHighlights = "No Highlights Yet"
    const val HighlightEmptyStateDesc = "As you use apps, screenshots are captured and processed using Google ML Kit to extract text (OCR) and recognize visual elements."
    const val HighlightTryDemo = "Try Demo Highlight"
    const val HighlightAllApps = "All Apps"
    const val HighlightTapToAnalyze = "Background analysis active..."
    const val HighlightWaiting = "Waiting for analysis..."
    const val HighlightCopied = "Copied to clipboard"
    const val HighlightAiActive = "AI Active (Starburst)"
    const val HighlightPenToggle = "Pen (Toggle Reasoning)"
    const val HighlightGrantUsageAccess = "Grant Usage Access"
    const val HighlightAnalyzingContent = "Analyzing content in background..."
    const val HighlightPreloadingQueued = "Preloading queued"
    const val HighlightSanitizingPii = "Sanitizing PII data (Privacy Shield active)..."
    const val HighlightDeduplicating = "Deduplicating session captures..."
    const val HighlightContextualizing = "Injecting historical & contextual timeline..."
    const val HighlightReasoning = "Synthesizing Gemini executive narrative..."
    const val HighlightAnalyzingUsage = "Analyzing usage activity & generating executive narratives..."
    const val HighlightGeminiEngine = "Gemini Reasoning Engine"
    const val HighlightAiNarrativeInsight = "AI Narrative Insight • %s"
    const val HighlightDailyNarrative = "Daily Executive Narrative • All Apps"
    const val HighlightPrivacyShieldActive = "Privacy Shield Active"
    const val HighlightPrivacyShieldDesc = "PII Redactor successfully detected and scrubbed sensitive data (emails, phone numbers, auth tokens, cards) locally on-device before Gemini reasoning."
    const val HighlightGotIt = "Got it"
    const val HighlightSanitized = "Sanitized"
    const val HighlightTasksNextSteps = "Detected Tasks & Next Steps"
    const val HighlightCopyTasks = "Copy Tasks"
    const val HighlightGenerateAiNarrativeApp = "Generate AI Narrative for this app"
    const val HighlightSynthesizeDailyNarrative = "Synthesize Daily Gemini Narrative"
    const val HighlightAiActivityReasoning = "AI Activity Reasoning"
    const val HighlightAiReasoningDesc = "Turn your raw screen captures into meaningful narratives. Data is processed via Gemini Cloud for reasoning. No data is used for model training."
    const val HighlightEnableAiNarratives = "Enable AI Narratives"
    const val HighlightNoActivityCaptured = "No activity captured yet. Use your apps or tap Sync to load your recent timeline activity."
    const val HighlightRawCaptures = "Raw Captures"
    const val HighlightReasoningDots = "Reasoning..."
    const val HighlightAiSynthesis = "AI Synthesis"

    // Real Data & Device Sync
    const val RealDataSyncTitle = "Sync Device Usage"
    const val RealDataSyncDesc = "Sync real app activity from your device"
    const val RealDataSyncButton = "Sync Real Data"
    const val RealDataPermissionBannerTitle = "Usage Access Required"
    const val RealDataPermissionBannerDesc = "Grant Usage Access so Timeline can track and analyze your real device app activity."
    const val RealDataGrantButton = "Grant Usage Access"
    const val RealDataSyncing = "Syncing device usage..."
    const val RealDataSyncedSuccess = "Synced %d real sessions from your device"
    const val RealDataNoActivityYet = "No real device activity recorded yet today. Open some apps on your device and tap Sync!"
    const val RealDataActiveTrackingNotice = "Live tracking is active. Real usage will update continuously."

    // Insights Dashboard
    const val InsightsOverview = "Overview"
    const val InsightsApps = "Apps"
    const val InsightsTrends = "Trends"
    const val InsightsPatterns = "Patterns"
    const val InsightsUsageUp = "Your usage is up"
    const val InsightsUsageDown = "Your usage is down"
    const val InsightsVsPrevious = "vs previous 7 days"
    const val InsightsBiggestPattern = "Your biggest pattern"
    const val InsightsMostUsedApp = "Most used app"
    const val InsightsMostActiveDay = "Most active day"
    const val InsightsWhereTimeGoes = "WHERE YOUR TIME GOES"
    const val InsightsTopAppsDesc = "Here are your top apps by usage."
    const val InsightsSeeAllApps = "See all %d apps"
    const val InsightsUsageTrend = "USAGE TREND"
    const val InsightsUsageMoreThanLast = "You're using your phone more than last week."
    const val InsightsWhenUsePhone = "WHEN YOU USE YOUR PHONE"
    const val InsightsUsageAfterSeven = "of your usage happens after 7 PM."
    const val InsightsFoundPatterns = "We found a few patterns in your usage."
    const val InsightsPeakAtNight = "Your phone time peaks at night"
    const val InsightsMostActiveHour = "%d PM is your most active hour."
    const val InsightsYouSpent = "You spent %s."
    const val InsightsLongSessions = "%s dominates your long sessions"
    const val InsightsLongestSessionWas = "Your longest session was %s."
    const val InsightsHeaviestDays = "%s are your heaviest days"
    const val InsightsHeaviestDayUsage = "%s of usage."
    const val InsightsExploreAllPatterns = "Explore all patterns"

    // Session Detail
    const val SessionStarted = "Started"
    const val SessionEnded = "Ended"
    const val SessionDuration = "Duration"
    const val SessionCount = "%d %s"
    const val SessionCountSingle = "session"
    const val SessionCountPlural = "sessions"
    const val SessionPrev = "Prev"
    const val SessionNext = "Next"
    const val SessionNoScreenshots = "No screenshots available"

    // Settings
    const val SettingsTitle = "Settings"
    const val SettingsCategoryPreference = "PREFERENCE"
    const val SettingsCategoryTracking = "TRACKING"
    const val SettingsCategoryCapture = "CAPTURE"
    const val SettingsCategoryPermissions = "PERMISSIONS"
    const val SettingsCategoryData = "DATA"
    const val SettingsCategoryAbout = "ABOUT"
    const val SettingsCategorySupport = "SUPPORT"
    const val SettingsHighlightsReasoning = "Highlights & Reasoning"
    const val SettingsManageSubscription = "Manage Subscription"
    const val SettingsUsageTrackingTitle = "Enable App Interaction"
    const val SettingsUsageTrackingDesc = "Record app interaction."
    const val SettingsScreenshotCaptureTitle = "Enable Screenshot Capture"
    const val SettingsScreenshotCaptureDesc = "Save snapshots during sessions."
    const val SettingsAppExclusionsTitle = "Manage App Exclusion"
    const val SettingsAppExclusionsDesc = "Manage excluded apps."
    const val SettingsExclusionTrialOrPro = "Unlock with Trial or Pro"
    const val SettingsDataRetentionTitle = "Adjust Data Retention"
    const val SettingsDataRetentionDesc = "Keep data for %d days"
    const val SettingsDataRetentionSelect = "Select retention period"
    const val SettingsScheduleFrequency = "Schedule and Frequency"
    const val SettingsReasoningMode = "Reasoning Mode"
    const val SettingsFrequencyLabel = "Frequency (%dX)"
    const val SettingsDaysLabel = "%d days"
    const val SettingsAboutTimelineTitle = "About the $AppName app"
    const val SettingsAboutTimelineDesc = "Learn more about the application."
    const val SettingsAppVersionTitle = "Application version"
    const val SettingsAppVersionValue = "1.0.0 (Stable)"
    const val SettingsContactUsTitle = "Contact Support"
    const val SettingsContactUsDesc = "Need help? Reach out to us."
    const val SettingsReportBugsTitle = "Report a bug"
    const val SettingsReportBugsDesc = "Found an issue? Let us know."
    const val SettingsUpgradeTitle = "You're a free user, get more"
    const val SettingsMadeByMo = "Made with ❤ by Mo"
    const val SettingsAccountOptions = "Account Options"
    const val SettingsSignOut = "Sign Out"
    const val SettingsSignIn = "Sign In"
    const val SettingsUnlockPro = "Unlock with Pro"

    // Notifications
    const val NotificationTrackingActiveTitle = "$AppName Tracking Active"
    const val NotificationTrackingActiveContent = "Recording activity journal..."
    const val NotificationAccessibilityLostTitle = "Screenshot capture stopped"
    const val NotificationAccessibilityLostContent = "Tap to re-enable accessibility permission"

    // Paywall
    const val PaywallUnlimitedInsights = "Unlimited insights."
    const val PaywallOneSimplePlan = "One simple plan."
    const val PaywallUnlockDeeper = "Unlock deeper insights."
    const val PaywallGoBeyond = "Go beyond 14 days and keep your data longer."
    const val PaywallLimitedTime = "LIMITED TIME"
    const val Paywall50Off = "20% off for 14 days"
    const val PaywallThenPrice = "Then $3.99 / month"
    const val PaywallPro = "PRO"
    const val PaywallTimelinePro = "Timeline PRO"
    const val PaywallMonthlyPrice = "$3.99 / month"
    const val PaywallUnlimitedHistory = "Unlimited history"
    const val PaywallDailyMonthlyDigest = "Daily & monthly digest"
    const val PaywallAdvancedInsights = "Advanced insights"
    const val PaywallPrioritySupport = "Priority support"
    const val PaywallMonthlyOption = "Monthly"
    const val PaywallMonthlyBilling = "$3.99 / billed monthly"
    const val PaywallYearlyOption = "Yearly"
    const val PaywallYearlyBilling = "$38.33 / pay after free trial"
    const val PaywallSave50 = "Save 20%"
    const val PaywallStartTrial = "Start 7-Day Free Trial"
    const val PaywallCancelAnytime = "Cancel anytime. No commitments."

    // Accessibility / Content Descriptions
    const val ContentDescClose = "Close"
    const val ContentDescBack = "Back"
    const val ContentDescSettings = "Settings"
    const val ContentDescExpand = "Expand"
    const val ContentDescCollapse = "Collapse"
    const val ContentDescPrevSession = "Previous Session"
    const val ContentDescNextSession = "Next Session"
    const val ContentDescAppIcon = "App Icon"
    const val ContentDescScreenshot = "Screenshot"
    const val ContentDescSessionSegment = "Session segment"

    // Permission Screen
    const val PermissionModeTitle = "How would you prefer to see your highlights?"
    const val PermissionModeSubtitle = "Choose your preferred highlight style and frequency."
    const val PermissionModeConciseBrief = "Brief summary: Focused check-ins & peak productivity."
    const val PermissionModeDetailedBrief = "Comprehensive breakdown: Active digital workflows across apps."
    const val PermissionModeBalancedBrief = "Balanced daily narrative and smart summaries."
    const val PermissionModeBalanced = "Balanced"
    const val PermissionModeConcise = "Concise"
    const val PermissionModeDetailedPro = "Detailed Pro Mode"
    const val PermissionTimingTitle = "Highlight Timing & Frequency"
    const val PermissionConfirmStart = "Confirm & Start"
    const val PermissionAccessibilityPrivacy = "Accessibility & Privacy"
    const val PermissionAccessibilityPrivacyDesc = "Timeline uses Accessibility to detect app switches and capture visual context for your daily highlights. Data processing happens on-device and through secure cloud services to improve app functionality and deliver the best highlights."
}
